Linky.Client/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Linky.Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

        
    
        

Linky.Client/Controllers/URLController.cs
using Microsoft.AspNetCore.Mvc;

namespace Linky.Client.Controllers
{
    public class URLController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Linky.Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Welcome";
}

<section class="landing py-5">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4">
                <img class="img-fluid" src="~/img/icon2.png" alt="" style="" />
            </div>
            <div class="col-lg-8">
                <h1 class="display-4">More than just shorter links </h1>
                <p class="lead">
                    Build your brand's recognition and get detailed insights on how your links are performing.
                </p>
            </div>
        </div>

    </div>

</section>
<section class="features" id="features">
    <div class="container">
        <div class="url-shorten-feature">
            <form class="url-shorten-form" id="url-shorten-form" action="/Home/ShortenAction" >
                <div>
                    <input type="text" class="url-input" name="urlToShorten" placeholder="Shorten a link here..." />
                    <span class="alert"></span>
                </div>
                <button type="submit" class="btn btn-lg" style="">Shorten It!</button>
            </form>
            <div class="url-shorten-results"></div>
        </div>
    </div>

</section>

Linky.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Linky.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Linky.Client.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Linky.Client</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="URL" asp-action="Index">All Links</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Index">Users</a>
                        </li>
                    </ul>
                </div>

                <a class="btn btn-outline-success my-2 my-sm-0 btn-login"
                asp-controller="Authentication"
                asp-action="Login">
                Login
                </a>
                <span style="padding: 5px;"></span>
                <a class="btn btn-outline-primary my-2 my-sm-0 btn-register"
                   asp-controller="Authentication"
                   asp-action="Register">
                    Register
                </a>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Linky
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Linky.Client/Views/URL/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    var CurrrentDateTime = DateTime.UtcNow;
}
<h1>Weclome to this App</h1>
<p>@CurrrentDateTime</p>